steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-Django
    args:
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-django:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-django:latest
      - --context=./backend
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-Nginx
    args:
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-nginx:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-nginx:latest
      - --context=./frontend
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: Gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials cluster-1 --zone=us-central1-a &&
        gcloud secrets versions access "latest" --secret service-account --format='get(payload.data)' | tr '_-' '/+' | base64 -d > service-account.txt &&
        gcloud secrets versions access "latest" --secret google-maps-api-key --format='get(payload.data)' | tr '_-' '/+' | base64 -d > google_maps_key.txt &&
        gcloud secrets versions access "latest" --secret oauth-secret --format='get(payload.data)' | tr '_-' '/+' | base64 -d > oauth-secret.txt

  - name: "gcr.io/$PROJECT_ID/helm"
    id: Helm-Upgrade
    entrypoint: "bash"
    args:
      - "-c"
      - |
        helm upgrade ignite-logistics-${_APP_ENV} ./helm -f ./helm/values/${_APP_ENV}.yaml --namespace ${_APP_ENV} --set django.tag=${COMMIT_SHA} --set nginx.tag=${COMMIT_SHA} --set google.project=$PROJECT_ID --set-file google.sa=service-account.txt --set-file google.maps_key=google_maps_key.txt --set-file google.oauth_secret=oauth-secret.txt
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"
