steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-Django
    args:
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-django:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-django:latest
      - --context=./backend
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-Nginx
    args:
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-nginx:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_APP_ENV}-nginx:latest
      - --context=./frontend
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: Gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials cluster-1 --zone=us-central1-a

  - name: "gcr.io/$PROJECT_ID/helm"
    id: Helm-Upgrade
    entrypoint: "bash"
    args:
      - "-c"
      - |
        helm upgrade ignite-logistics-${_APP_ENV} ./helm -f ./helm/values/${_APP_ENV}.yaml --namespace ${_APP_ENV} --set django.tag=${COMMIT_SHA} --set nginx.tag=${COMMIT_SHA} --set google.project=$PROJECT_ID
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"
