apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: google-cert
spec:
  domains:
    - {{ .Values.google.domain }}

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-tls
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.k8s.namespace }}-ip"
    networking.gke.io/managed-certificates: google-cert
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
spec:
  backend:
    serviceName: nginx-svc
    servicePort: 80
