apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    cloud.google.com/app-protocols: '{"http":"HTTP"}'
    networking.gke.io/internal-load-balancer-subnet: "gke-subnet"
spec:
  type: LoadBalancer
  selector:
    app: nginx-dep
    
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
