k8s:
  namespace: stage

db:
  conn: proxy
  name: stage-db
  user: stage-user

  project: ignite-logistics-db-dev
  instance: ignite-logistics-instance-dev

google:
  domain: stage.ignite-logistics.com
  static_bucket: ignite-logistics-static-dev
