k8s:
  api:
    memory:
      request: "128Mi"
      limit: "512Mi"
    cpu:
      request: .2
      limit: 1
    replicas: 1
    max_replicas: 1
    target_cpu: 80
    target_mem: 512Mi

  nginx:
    memory:
      request: "5Mi"
      limit: "50Mi"
    cpu:
      request: .1
      limit: .5
    replicas: 1
    max_replicas: 1
    target_cpu: 80
    target_mem: 50Mi

db:
  conn: local
  password: "null"
  cloudsqlproxy: gcr.io/cloudsql-docker/gce-proxy:1.18.0

django:
  key: "null"
  tag: latest
  email: fakeemail@gmail.com
  password: "null"

nginx:
  tag: latest

google:
  region: us-central1
  project: "null"
  sa: "null"
  oauth_id: "null"
  oauth_secret: "null"
